# Pandas - operations

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({'col1':[1,2,3,4],
                   'col2':[444,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [4]:
df['col2'].unique()

array([444, 555, 666])

In [5]:
len(df['col2'].unique())

3

In [6]:
df['col2'].nunique()

3

In [7]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [12]:
df[(df['col1']>2) & (df['col2']==444) ]

   col1  col2 col3
3     4   444  xyz

In [10]:
df['col1']>2

0    False
1    False
2     True
3     True
Name: col1, dtype: bool

In [13]:
def times2(x):
    return x*2

In [14]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [15]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [16]:
df['col2'].apply(lambda x: x*2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [20]:
df.drop('col1',axis=1,inplace = True)

In [21]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [25]:
df.sort_values(by='col2')

   col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

In [26]:
df.isnull()

    col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [27]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
       'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

In [28]:
df = pd.DataFrame(data)

In [29]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [30]:
df.pivot_table(values='D',index=['A','B'],columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN