# Pandas - DataFrames

In [5]:
import numpy as np
import pandas as pd

In [6]:
from numpy.random import randn

In [7]:
np.random.seed(101)

In [9]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [10]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [11]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [13]:
type[df['W']]

type[A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64]

In [14]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.W

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [17]:
df['X']

A    1.693723
B    0.390528
C    0.072960
D   -0.754070
E    1.901755
Name: X, dtype: float64

In [18]:
df[['W','Z']]

          W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [20]:
df['new'] = df['W'] + df['Y']

In [21]:
df

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [24]:
df.drop('new',axis=1,inplace = True)

In [25]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [27]:
df.drop('E',axis=0)

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752

In [28]:
df.shape

(5, 4)

In [29]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [30]:
df[['Z','X']]

          Z         X
A -1.159119  1.693723
B  0.184502  0.390528
C  0.329646  0.072960
D  0.484752 -0.754070
E  1.996652  1.901755

In [31]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [33]:
df.loc['C']

W    0.807706
X    0.072960
Y    0.638787
Z    0.329646
Name: C, dtype: float64

In [34]:
df.iloc[2]

W    0.807706
X    0.072960
Y    0.638787
Z    0.329646
Name: C, dtype: float64

In [35]:
df.loc['B','Y']

np.float64(0.16690463609281317)

In [36]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  0.302665 -1.706086
B -0.134841  0.166905

In [39]:
booldf = df > 0

In [40]:
booldf

       W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [41]:
df[df>0]

          W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [42]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [44]:
df['W'] > 0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [46]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [47]:
df[df['W']>0]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [50]:
df[df['Z'] < 0]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119