In [10]:
import numpy as np

In [11]:
import pandas as pd

In [17]:
from numpy.random import randn

In [18]:
outside = ['G1','G1','G1','G2','G2','G2']
inside  = [1,2,3,1,2,3]
hier_index =  list(zip(outside,inside))
heir_index = pd.MultiIndex.from_tuples(hier_index)

In [19]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [20]:
inside

[1, 2, 3, 1, 2, 3]

In [21]:
heir_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [22]:
list(zip(outside,inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [24]:
df = pd.DataFrame(randn(6,2),heir_index,['A','B'])

In [25]:
df

             A         B
G1 1 -0.205655  0.681463
   2  0.891655 -1.181928
   3  0.889789  0.248071
G2 1 -0.832184  1.096744
   2 -0.031514  0.130282
   3  0.178602  0.057691

In [27]:
df.loc['G1'].loc[1]

A   -0.205655
B    0.681463
Name: 1, dtype: float64

In [29]:
df.index.names = ['Groups','Num']

In [30]:
df

                   A         B
Groups Num
G1     1   -0.205655  0.681463
       2    0.891655 -1.181928
       3    0.889789  0.248071
G2     1   -0.832184  1.096744
       2   -0.031514  0.130282
       3    0.178602  0.057691

In [32]:
df.loc['G2'].loc[2]

A   -0.031514
B    0.130282
Name: 2, dtype: float64