# Missing Data

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [4]:
df = pd.DataFrame(d)

In [5]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [7]:
df.dropna(axis = 1)

   C
0  1
1  2
2  3

In [8]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [9]:
df.dropna(thresh = 2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [10]:
df.fillna(value='FILL VALUE')

            A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [12]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64